// Auto-generated cold-start sub-core classifier
// Uses ONLY pre-launch features (grid/block dims, nregs, shmem)
// Generated by coldstart_classifier.py
// Modified for C++11 compatibility (no ODR-use of static constexpr arrays)

#ifndef COLDSTART_CLASSIFIER_H
#define COLDSTART_CLASSIFIER_H

#include <algorithm>

class ColdStartClassifier {
public:
    static const int NUM_FEATURES = 14;
    static const int NUM_CLASSES = 4;
    static const int NUM_NODES = 17;

    // Predict optimal sub-core count from pre-launch features
    static int predict(const double features[NUM_FEATURES]) {
        static const double SCALER_MEAN[14] = {236.8020942408, 365.8596858639, 57137.7591623037, 25.0756544503, 1715.9675392670, 168.4879581152, 39.2824607330, 342.3246073298, 1.8057591623, 714.2219895288, 2.9600261780, 7709.1937172775, 17.7061436518, 0.0754871564};
        static const double SCALER_STD[14] = {1107.3292205655, 183.5276694203, 283419.3850886149, 13.4062493814, 3035.3355333461, 1042.7924103634, 372.9846249182, 214.1849065906, 2.8807845653, 3542.7423136077, 13.8416152571, 4530.3896936231, 35.9522683941, 0.0751621725};

        static const int CHILDREN_LEFT[17] = {1, -1, 3, 4, 5, -1, -1, 8, -1, -1, 11, 12, -1, -1, 15, -1, -1};
        static const int CHILDREN_RIGHT[17] = {2, -1, 10, 7, 6, -1, -1, 9, -1, -1, 14, 13, -1, -1, 16, -1, -1};
        static const int FEATURE[17] = {3, -2, 0, 4, 13, -2, -2, 2, -2, -2, 5, 11, -2, -2, 7, -2, -2};
        static const double THRESHOLD[17] = {-0.9007481635, -2.0000000000, -0.1050293744, 0.6193820834, -0.4430374503, -2.0000000000, -2.0000000000, -0.1826330945, -2.0000000000, -2.0000000000, 0.4272298366, -0.2889803797, -2.0000000000, -2.0000000000, -0.5524413735, -2.0000000000, -2.0000000000};

        static const double VALUE[17][4] = {
            {764.0, 764.0, 764.0, 764.0},
            {3.0, 15.0, 565.0, 0.0},
            {761.0, 749.0, 199.0, 764.0},
            {699.0, 740.0, 199.0, 227.0},
            {699.0, 736.0, 0.0, 0.0},
            {254.0, 0.0, 0.0, 0.0},
            {445.0, 736.0, 0.0, 0.0},
            {0.0, 4.0, 199.0, 227.0},
            {0.0, 0.0, 0.0, 227.0},
            {0.0, 4.0, 199.0, 0.0},
            {62.0, 9.0, 0.0, 537.0},
            {18.0, 9.0, 0.0, 484.0},
            {14.0, 0.0, 0.0, 466.0},
            {4.0, 9.0, 0.0, 18.0},
            {44.0, 0.0, 0.0, 53.0},
            {44.0, 0.0, 0.0, 0.0},
            {0.0, 0.0, 0.0, 53.0}
        };

        static const int CLASSES[4] = {1, 2, 3, 4};

        double scaled[NUM_FEATURES];
        for (int i = 0; i < NUM_FEATURES; i++) {
            scaled[i] = (features[i] - SCALER_MEAN[i]) / SCALER_STD[i];
        }
        int node = 0;
        while (CHILDREN_LEFT[node] != -1) {
            if (scaled[FEATURE[node]] <= THRESHOLD[node])
                node = CHILDREN_LEFT[node];
            else
                node = CHILDREN_RIGHT[node];
        }
        int best = 0;
        double max_val = VALUE[node][0];
        for (int c = 1; c < NUM_CLASSES; c++) {
            if (VALUE[node][c] > max_val) {
                max_val = VALUE[node][c];
                best = c;
            }
        }
        return CLASSES[best];
    }

    // Convenience: predict from raw grid/block parameters
    static int predict_from_launch_params(
            int grid_x, int grid_y, int grid_z,
            int block_x, int block_y, int block_z,
            int nregs, int shmem) {
        int grid_size = grid_x * grid_y * grid_z;
        int block_size = block_x * block_y * block_z;
        double features[NUM_FEATURES] = {
            static_cast<double>(grid_size),
            static_cast<double>(block_size),
            static_cast<double>(grid_size) * block_size,
            static_cast<double>(nregs),
            static_cast<double>(shmem),
            static_cast<double>(grid_x),
            static_cast<double>(grid_y),
            static_cast<double>(block_x),
            static_cast<double>(block_y),
            static_cast<double>(grid_size) * block_size / 80.0,
            static_cast<double>(grid_size) / 80.0,
            static_cast<double>(nregs) * block_size,
            block_size > 0 ? static_cast<double>(shmem) / block_size : 0.0,
            std::min(static_cast<double>(block_size) / 1024.0, 1.0) * std::min(static_cast<double>(grid_size) / 80.0, 1.0)
        };
        return predict(features);
    }
};

#endif // COLDSTART_CLASSIFIER_H
