// Auto-generated cold-start sub-core classifier
// Uses ONLY pre-launch features (grid/block dims, nregs, shmem)
// Generated by coldstart_classifier.py

#ifndef COLDSTART_CLASSIFIER_H
#define COLDSTART_CLASSIFIER_H

#include <algorithm>

class ColdStartClassifier {
public:
    static constexpr int NUM_FEATURES = 14;
    static constexpr int NUM_CLASSES = 4;
    static constexpr int NUM_NODES = 47;

    // Feature names: grid_size, block_size, total_threads, nregs, shmem,
    // grid_dim_x, grid_dim_y, block_dim_x, block_dim_y, threads_per_sm,
    // blocks_per_sm, reg_footprint, shmem_per_thread, occupancy_proxy

    // Scaler parameters
    static const double SCALER_MEAN[NUM_FEATURES];
    static const double SCALER_STD[NUM_FEATURES];

    // Decision tree structure
    static const int CHILDREN_LEFT[NUM_NODES];
    static const int CHILDREN_RIGHT[NUM_NODES];
    static const int FEATURE[NUM_NODES];
    static const double THRESHOLD[NUM_NODES];
    static const double VALUE[NUM_NODES][NUM_CLASSES];
    static const int CLASSES[NUM_CLASSES];

    // Predict optimal sub-core count from pre-launch features
    static int predict(const double features[NUM_FEATURES]) {
        double scaled[NUM_FEATURES];
        for (int i = 0; i < NUM_FEATURES; i++) {
            scaled[i] = (features[i] - SCALER_MEAN[i]) / SCALER_STD[i];
        }
        int node = 0;
        while (CHILDREN_LEFT[node] != -1) {
            if (scaled[FEATURE[node]] <= THRESHOLD[node])
                node = CHILDREN_LEFT[node];
            else
                node = CHILDREN_RIGHT[node];
        }
        int best = 0;
        double max_val = VALUE[node][0];
        for (int c = 1; c < NUM_CLASSES; c++) {
            if (VALUE[node][c] > max_val) {
                max_val = VALUE[node][c];
                best = c;
            }
        }
        return CLASSES[best];
    }

    // Convenience: predict from raw grid/block parameters
    static int predict_from_launch_params(
            int grid_x, int grid_y, int grid_z,
            int block_x, int block_y, int block_z,
            int nregs, int shmem) {
        int grid_size = grid_x * grid_y * grid_z;
        int block_size = block_x * block_y * block_z;
        double features[NUM_FEATURES] = {
            static_cast<double>(grid_size),
            static_cast<double>(block_size),
            static_cast<double>(grid_size) * block_size,
            static_cast<double>(nregs),
            static_cast<double>(shmem),
            static_cast<double>(grid_x),
            static_cast<double>(grid_y),
            static_cast<double>(block_x),
            static_cast<double>(block_y),
            static_cast<double>(grid_size) * block_size / 80.0,
            static_cast<double>(grid_size) / 80.0,
            static_cast<double>(nregs) * block_size,
            block_size > 0 ? static_cast<double>(shmem) / block_size : 0.0,
            std::min(static_cast<double>(block_size) / 1024.0, 1.0) *
                std::min(static_cast<double>(grid_size) / 80.0, 1.0)
        };
        return predict(features);
    }
};

enum ColdStartClassifierMode {
    COLDSTART_CLASSIFIER_DEFAULT = 0,
    COLDSTART_CLASSIFIER_PERFORMANCE_AGGRESSIVE = 1
};

inline int coldstart_classifier_predict(
        int grid_x, int grid_y, int grid_z,
        int block_x, int block_y, int block_z,
        int nregs, int shmem,
        ColdStartClassifierMode mode = COLDSTART_CLASSIFIER_DEFAULT) {
    (void)mode;
    return ColdStartClassifier::predict_from_launch_params(
        grid_x, grid_y, grid_z, block_x, block_y, block_z, nregs, shmem);
}

#endif // COLDSTART_CLASSIFIER_H
